# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-16 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('address', models.CharField(max_length=60)),
                ('cellphone', models.CharField(max_length=10)),
                ('birthday', models.DateField()),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('last_login', models.DateTimeField()),
            ],
        ),
    ]
