# Generated by Django 2.0 on 2017-12-28 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('IB', '0002_auto_20171228_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('event_description', models.TextField()),
                ('discount', models.FloatField()),
                ('eventType', models.CharField(choices=[('shipping', 'shipping'), ('seasonings', 'seasonings'), ('special', 'special')], default='special', max_length=15)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount', to='IB.Category')),
            ],
        ),
    ]
