# Generated by Django 2.0 on 2017-12-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='End_date',
            field=models.DateTimeField(default='2017-10-10 14:20:51'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discount',
            name='Start_date',
            field=models.DateTimeField(default='2017-10-10 14:20:51'),
            preserve_default=False,
        ),
    ]
