# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=30, unique=True)),
                ('bookname', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=30)),
                ('publisher', models.CharField(max_length=30)),
                ('publish_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('photo', models.URLField(blank=True)),
                ('on_shelve', models.BooleanField()),
                ('state', models.BooleanField()),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('language', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=10)),
            ],
        ),
    ]
