# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IB', '0003_auto_20171127_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_cost',
            new_name='books_cost',
        ),
        migrations.RemoveField(
            model_name='book',
            name='on_shelve',
        ),
        migrations.RemoveField(
            model_name='orderlist',
            name='seller',
        ),
        migrations.AddField(
            model_name='order',
            name='shipment_cost',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
