# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IB', '0006_auto_20171129_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='photo',
        ),
    ]
