# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IB', '0007_remove_account_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('literature', 'Literature'), ('art', 'Art'), ('life', 'Life'), ('comics', 'Comics'), ('science', 'Science'), ('society', 'Society'), ('language', 'Language'), ('computer', 'Computer'), ('else', 'Else')], default='else', max_length=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('FR', 'English'), ('CH', 'Chinese')], default='CH', max_length=10),
        ),
    ]
