# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-16 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('IB', '0001_initial'),
        ('Account', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_cost', models.IntegerField()),
                ('books_cost', models.IntegerField()),
                ('order_date', models.DateTimeField()),
                ('shipment_date', models.DateTimeField(null=True)),
                ('arrival_date', models.DateTimeField(null=True)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.Account')),
            ],
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_quantity', models.PositiveIntegerField(default=1)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IB.Book')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
        ),
    ]
