# Generated by Django 2.0 on 2017-12-27 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20171228_0339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlist',
            old_name='book_price',
            new_name='price',
        ),
    ]
