# Generated by Django 2.0 on 2017-12-31 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20171228_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
